@include('layouts.header')
<!-- start about me-->
<section id="about" xmlns="http://www.w3.org/1999/html">
    <div class="container">
        {{--<div class="row">--}}
        {{--<div class="col-md-6 heading">--}}
        {{--<h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><div>Search a destination<span class="hot">new</span></div></h2>--}}
        {{--</div>--}}
        {{--<div class="container col-md-6 edit_dest" id="portfolio">--}}
        {{--<div class="row">--}}
        {{--<form method="" action="{{URL::to('search/')}}">--}}
        {{--<div class="col-sm-12">--}}
        {{--<input type="text" class="form-control form-control-lg" required id="searchfield" name="destination">--}}
        {{--<button type="submit" id="search">--}}
        {{--<i class="fa fa-search" aria-hidden="true"></i>--}}
        {{--</button>--}}
        {{--</div>--}}
        {{--</form>--}}
        {{--</div>--}}
        {{--</div>--}}
        {{--</div>--}}
        <div class="col-md-6 heading">
            <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><div>Best offers!<span class="hot">HOT</span><span>Grab your best offer for the best price.</span></div></h2>
        </div>
        <div class="container" id="portfolio">
            <div class="row">
                <p>
                    Code of Good Practices
                    Our mission is to empower people to experience the world, by offering the world's best places to stay and greatest places and attractions to visit in the most convenient way. In order to achieve this goal, we will live up to the following good practices:

                    We care about you: and therefore offer our Platform and customer service in 40+ languages
                    We bring and allow you to experience: 1.5m+ properties from high (high) end to whatever serves your needs for your next stay in a hotel, motel, hostel, B&B, etc. wherever on the planet
                    We bring and allow you to experience attractions and other Trip Providers
                    We can facilitate the payment of any (entrance) fee, purchase or rental of any Trip product and service which uses our payment service
                    We help you (24/7): our customer service centers are here to help you 24-7-365-40+
                    We listen to you: our Platform is the product of what YOU (the users) prefer and find most convenient when using our service
                    We hear you: we show uncensored reviews (of customers who have actually stayed)
                    We promise you an informative, user-friendly website that guarantees the best available prices.
                    We Price Match
                    Introduction TCs
                    These terms and conditions, as may be amended from time to time, apply to all our services directly or indirectly (through distributors) made available online, through any mobile device, by email, or by telephone. By accessing, browsing, and using our (mobile) website or any of our applications through whatever platform (hereafter collectively referred to as the "Platform") and/or by completing a reservation, you acknowledge and agree to have read, understood, and agreed to the terms and conditions set out below (including the privacy statement).

                    These pages, the content, and infrastructure of these pages and the online reservation service (including the facilitation of payment service) provided by us on these pages and through the website are owned, operated, and provided by Booking.com B.V. and are provided for your personal, non-commercial (B2C) use only, subject to the terms and conditions set out below. The relationship that we have with the Trip Providers are governed by separate terms and conditions which govern the (B2B) commercial relationship we have with each of these Trip Providers. Each Trip Provider acts in a professional manner vis-à-vis Booking.com when making its product and/or service available on or through Booking.com (both for its business-to-business ("B2B") and/or business-to-consumer ("B2C") relationship). Note that Trip Providers may have, declare applicable, and/or require (acceptance of) – in addition to the policies and fine print as disclosed on the website, their own (delivery/shipping/carriage/usage) terms and conditions and house rules for the use, access, and consummation of the Trip (which may include certain disclaimers and limitations of liability).

                    0. Definitions
                    "Booking.com," "us," "we," or "our" means Booking.com B.V., a limited liability company incorporated under the laws of the Netherlands, and having its registered address at Herengracht 597, 1017 CE, Amsterdam, the Netherlands. "Platform" means the (mobile) website and app on which the Trip Service is made available owned, controlled, managed, maintained, and/or hosted by Booking.com. "Trip" means the various different travel products and services that can be ordered, acquired, purchased, bought, paid, rented, provided, reserved, combined, or consummated by you from the Trip Provider.

                    "Trip Provider" means the professional provider of accommodations (e.g. hotel, motel, apartment, bed & breakfast), attractions (e.g. (theme) parks, museums, sightseeing tours), transportation provider (e.g. car rentals, cruises, rail, airport rides, bus tours, transfers), tour operators, travel insurances, and any other travel or related product or service as from time to time available for Trip Reservation on the Platform (whether B2B or B2C).

                    "Trip Service" means the online purchase, order, (facilitated) payment, or reservation service as offered or enabled by Booking.com in respect to various products and services as from time to time made available by Trip Providers on the Platform.

                    "Trip Reservation" means the order, purchase, payment, booking, or reservation of a Trip.

                    1. Scope & Nature of Our Service
                    Through the Platform, we (Booking.com B.V. and its affiliate (distribution) partners) provide an online platform through which Trip Providers—in their professional conduct of business (i.e. B2C or B2B)—can advertise, market, sell, promote, and/or offer (as applicable) their products and service for order, purchase, reservation, hire, and through which relevant visitors of the Platform can discover, search, compare, and make an order, reservation, purchase, or payment (i.e. the Trip Service). By using or utilizing the Trip Service (e.g. by making a Trip Reservation through the Trip Service), you enter into a direct (legally binding) contractual relationship with the Trip Provider with which you make a reservation or purchase a product or service (as applicable). From the point at which you make your Trip Reservation, we act solely as an intermediary between you and the Trip Provider, transmitting the relevant details of your Trip Reservation to the relevant Trip Provider(s) and sending you a confirmation email for and on behalf of the Trip Provider. Booking.com does not (re)sell, rent out, offer any (travel) product or service.

                    When rendering our Trip Service, the information that we disclose is based on the information provided to us by Trip Providers. As such, the Trip Providers that market and promote their Trip on the Platform are given access to our systems and Extranet through which they are fully responsible for updating all rates/fees/prices, availability, policies and conditions, and other relevant information which is displayed on our Platform. Although we will use reasonable skill and care in performing our Trip Service, we will not verify if, and cannot guarantee that all information is accurate, complete, or correct, nor can we be held responsible for any errors (including manifest and typographical errors), any interruptions (whether due to any (temporary and/or partial) breakdown, repair, upgrade, or maintenance of our Platform or otherwise), inaccurate, misleading, or untrue information or non-delivery of information. Each Trip Provider remains responsible at all times for the accuracy, completeness, and correctness of the (descriptive) information (including the rates/fees/prices, policies and conditions, and availability) displayed on our Platform. Our Platform does not constitute and should not be regarded as a recommendation or endorsement of the quality, service level, qualification, or (star) rating of any Trip Provider (or its facilities, venue, vehicles, (main or ancillary) products or services) made available.

                    Our Trip Service is made available for personal and non-commercial use only. Therefore, you are not allowed to resell, deep link, use, copy, monitor (e.g. spider, scrape), display, download, or reproduce any content or information, software, reservations, tickets, products, or services available on our Platform for any commercial or competitive activity or purpose.

                    2. Prices, Crossed-Out Rates & We Price Match
                    The prices as offered by the Trip Providers on our Platform are highly competitive. All prices for your Trip are displayed including VAT/sales tax and all other taxes (subject to change of such taxes) and fees, unless stated differently on our Platform or the confirmation email/ticket. Ticket prices are per person or group and subject to validity or expiration as indicated on the ticket, if applicable. Applicable fees and taxes (including tourist/city tax) may be charged by the Trip Provider in the event of a no-show or cancellation.

                    Sometimes cheaper rates are available on our Platform for a specific stay, product, or service, however, these rates made available by Trip Providers may carry special restrictions and conditions, for example non-cancelable and non-refundable. Check the relevant product, service, and reservation conditions and details thoroughly for any such conditions prior to making your reservation.

                    The crossed-out rate shown for rooms is based on the third-highest current price of the Trip Provider for your Trip with the same reservation or purchase conditions in a 30-day window around your check-in or consummation date (15 days before and 15 days after check-in or consummation date; if less than 15 days are between today and the check-in or consummation date, we will use the corresponding number of days after the check-in or consummation date to result in a 30-day total). To ensure we are making a fair comparison, we always use the same Trip conditions (e.g. cancellation policy, ancillary products (such as meal plan) and Trip type). This means that you get the same Trip for a lower price, compared to other check-in or consummation dates at the same time of year.

                    We want you to pay the lowest price possible for your product and service of choice. If you find your product or service of choice booked through the Platform, with the same Trip conditions, at a lower rate on the Internet after you have made a Trip reservation through us, we will match the difference between our rate and the lower rate under the terms and conditions of the We Price Match.

                    The currency converter is for information purposes only and should not be relied upon as accurate and real time; actual rates may vary.

                    Obvious errors and mistakes (including misprints) are not binding.

                    All special offers and promotions are marked as such. If they are not labeled as such, you cannot derive any rights in the event of obvious errors or mistakes.

                    3. Privacy and Cookies
                    Booking.com respects your privacy. Please take a look at our Privacy and Cookies Policy for further information.

                    4. Free of charge for consumers, only Trip Providers pay!
                    Unless indicated otherwise, our service is free of charge for consumers because, unlike many other parties, we will not charge you for our Trip Service or add any additional (reservation) fees to the rate. You will pay the Trip Provider the relevant amount as indicated in the Trip Reservation (plus—insofar not included in the price—relevant applicable taxes, levies, and fees (if applicable)).

                    Trip Providers pay a commission (being a small percentage of the product price (e.g. room price)) to Booking.com after the end user has consummated the service or product of the Trip Provider (e.g. after the guest has stayed at (and paid) the accommodations). Trip Providers can improve their ranking by increasing their commission (Visibility Booster). The use of the Visibility Booster (by increasing the commission in return for a better position in the ranking) is at each Trip Provider's discretion and may be used from time to time and product to product offered. The algorithm of the ranking will take an increase in commission into account when determining the Default Ranking. Preferred partners pay a higher commission in return for a better position in the ranking.

                    Only Trip Providers which have a commercial relationship with Booking.com (through an agreement) will be made available on Platform (for their B2B and/or B2C promotion of their product). Booking.com is not an open platform (like Amazon or eBay) where end users can make their product available (no C2C platform); Booking.com does not allow non-professional parties to offer or sell their products on or through Booking.com.

                    5. Credit Card or Bank Transfer
                    If applicable and available, certain Trip Providers offer the opportunity for Trip Reservations to be paid (wholly or partly and as required under the payment policy of the Trip Provider) to the Trip Provider during the Trip Reservation process, by means of secure online payment (all to the extent offered and supported by your bank). For certain products and services, Booking.com facilitates (through third party payment processors) the payment of the relevant product or service (i.e. the payment facilitation service) for and on behalf of the Trip Provider (Booking.com never acts nor operates as the merchant of record). Payment is safely processed from your credit/debit card or bank account to the bank account of the accommodation provider through a third party payment processor. Any payment facilitated by us for and on behalf of, and transferred to the Trip Provider will in each case constitute a payment of (part of) the booking price by you of the relevant product or service in final settlement (bevrijdende betaling) of such (partial) due and payable price and you cannot reclaim such paid monies.

                    For certain (non-refundable) rates or special offers, note that Trip Providers may require that payment be made upfront by wire transfer (if available) or by credit card, and therefore your credit card may be pre-authorized or charged (sometimes without any option for refund) upon making the Trip Reservation. Check the (reservation) details of your product or service of choice thoroughly for any such conditions prior to making your Trip Reservation. You will not hold Booking.com liable or responsible for any (authorized, (allegedly) unauthorized or wrong) charge by the Trip Provider and not (re)claim any amount for any valid or authorized charge by the Trip Provider (including for pre-paid rates, no-show, and chargeable cancellation) of your credit card.

                    In the event of credit card fraud or unauthorized use of your credit card by third parties, most banks and credit card companies bear the risk and cover all the charges resulting from such fraud or misuse, which may sometimes be subject to a deductible (usually set at EUR 50 (or the equivalent in your local currency)). In the event that your credit card company or bank charges the deductible from you because of unauthorized transactions resulting from a reservation made on our Platform, we will pay you this deductible, up to an aggregate amount of EUR 50 (or the equivalent in your local currency). In order to indemnify you, make sure that you report this fraud to your credit card provider (in accordance with its reporting rules and procedures) and contact us immediately by email (customer.relations@booking.com). State "credit card fraud" in the subject line of your email and provide us with evidence of the charged deductible (e.g. policy of the credit card company). This indemnification only applies to credit card reservations made using Booking.com's secure server and the unauthorized use of your credit card resulted through our default or negligence and through no fault of your own while using the secure server.

                    6. Prepayment, Cancellation, No-shows, and The Fine Print
                    By making a Trip Reservation with a Trip Provider, you accept and agree to the relevant cancellation and no-show policy of that Trip Provider, and to any additional (delivery) terms and conditions of the Trip Provider that may apply to your Trip (including the fine print of the Trip Provider made available on our Platform and the relevant house rules of the Trip Provider), including for services rendered and/or products offered by the Trip Provider. The relevant (delivery/purchase/use/carrier) terms and conditions of an Trip Provider can be obtained with the relevant Trip Provider. The general cancellation and no-show policy of each Trip Provider is made available on our Platform on the Trip Provider information pages, during the reservation procedure and in the confirmation email or ticket (if applicable). Note that certain rates, fees, or special offers are not eligible for cancellation, refund, or change. Applicable city/tourist tax may still be charged by the Trip Provider in the event of a no-show or charged cancellation. Check the (reservation) details of your product or service of choice thoroughly for any such conditions prior to making your reservation. Note that a Trip Reservation which requires down payment or (wholly or partly) prepayment may be canceled (without a prior notice of default or warning) insofar the relevant (remaining) amount(s) cannot be collected in full on the relevant due or payment date in accordance with the relevant payment policy of the Trip Provider and the reservation. Cancellation and prepayment policies may vary per segment, product, or service of each Trip. Carefully read The Fine Print (below the Trip types or at the bottom of each Trip Provider page on our Platform) and important information in your reservation confirmation for additional policies as may be applied by the Trip Provider (e.g. in respect of age requirement, security deposit, non-cancellation/additional supplements for group bookings, extra beds/no free breakfast, pets/cards accepted). Late payment, wrong bank, debit or credit card details, invalid credit/debit cards or insufficient funds are for your own risk and account, and you will not be entitled to any refund of any (non-refundable) prepaid amount unless the Trip Provider agrees or allows otherwise under its (pre)payment and cancellation policy.

                    If you want to review, adjust, or cancel your Trip Reservation, revert to the confirmation email and follow the instructions therein. Note that you may be charged for your cancellation in accordance with the Trip Provider's cancellation, (pre)payment and no-show policy, or not be entitled to any repayment of any (pre)paid amount. We recommend that you read the cancellation, (pre)payment and no-show policy of the accommodation provider carefully prior to making your reservation, and remember to make further payments on time as may be required for the relevant reservation.

                    If you have a late or delayed arrival on the check-in date or only arrive the next day, make sure to (timely/promptly) communicate this with the Trip Provider so they know when to expect you to avoid cancellation of your Trip (Reservation) or charge of the no-show fee. Our customer service department can help you if needed with informing the Trip Provider. Booking.com does not accept any liability or responsibility for the consequences of your delayed arrival or any cancellation or charged no-show fee by the Trip Provider.

                    7. (Further) Correspondence and Communication
                    By completing a Trip Reservation, you agree to receive (i) an email which we may send you shortly prior to your arrival date, giving you information on your destination and providing you with certain information and offers (including third party offers to the extent that you have actively opted in for this information) relevant to your Trip (Reservation) and destination, and (ii) an email which we may send to you promptly after your stay inviting you to complete our guest review form. See our privacy and cookies policy for more information about how we may contact you.

                    Booking.com disclaims any liability or responsibility for any communication by or with the Trip Provider on or through its platform. You cannot derive any rights from any request to, or communication with the Trip Provider or (any form of) acknowledgement of receipt of any communication or request. Booking.com cannot guarantee that any request or communication will be (duly and timely) received/read by, complied with, executed, or accepted by the Trip Provider.

                    In order to duly complete and secure your Trip Reservation, you need to use your correct email address. We are not responsible or liable for (and have no obligation to verify) any wrong or misspelled email address, or inaccurate or wrong (mobile) phone number or credit card number.

                    Any claim or complaint against Booking.com or in respect to the Trip Service must be promptly submitted, but in any event within 30 days after the scheduled day of consummation of the product or service (e.g. check out date). Any claim or complaint that is submitted after the 30 days period may be rejected, and the claimant will forfeit the right to any (damage or cost) compensation.

                    Due to the continuous update and adjustments of rates and availability, we strongly suggest to make screenshots when making a reservation to support your position (if needed).

                    8. Ranking, Preferred Program, Stars and Guest Reviews
                    The default setting of the ranking of Suppliers on our Platform is "Booking.com Recommends" (or any similar wording); this is the Default Ranking. Note that the Default Ranking is created through a complex ever-changing and evolving system (algorithm) that considers a multitude of criteria in order to match searchers and accommodations in an optimal way. The actual ranking will be different for each customer and for each search as there are many criteria included, for example the popularity of an accommodation premise among our visitors (e.g. guest reviews), customer service history (including the number and type of guest complaints), certain booking-related data (e.g. number of bookings, cancellations, conversion rate, overbookings, availability, etc.) and the (past) browsing activities of a visitor. On-time payment of commission by accommodations and the commission percentage are also included in the algorithm of the Default Ranking. Note that for convenience we also offer other ways to rank Suppliers. A customer can choose to rank, for example, accommodations on the basis of lowest price first, review scores, accommodation type (etc.). A customer thus has full control on the presentation of the search results.

                    In certain cities and regions, Booking.com operates a preferred partnership program, allowing certain Trip Providers that meet and maintain the preferred program terms to be listed ahead of the rest of the Trip Providers in the default “Recommended” ranking for the relevant city/region. The preferred Trip Providers are marked with a “thumbs-up” symbol and in return for this high ranking, the preferred Trip Provider pays a higher commission. Only Trip Providers that meet and maintain certain qualification criteria can be listed as preferred.

                    The stars used for non-hotel accommodations (e.g. bed & breakfasts) do not correspond to the star ranking system as may be applicable to hotel accommodations.

                    Only customers who have stayed at the Accommodation will be invited by Booking.com to comment on their stay at the relevant accommodations and to provide a score for certain aspects of their stay. The completed guest review may be (a) uploaded onto the relevant Trip Provider's information page on our Platform for the sole purpose of informing (future) customers of your opinion of the service (level) and quality of the Trip Provider, and (b) (wholly or partly) used and placed by Booking.com at its sole discretion (e.g. for marketing, promotion, or improvement of our service) on our Platform or such social media platforms, newsletters, special promotions, apps, or other channels owned, hosted, used, or controlled by Booking.com and our business partners. In order to offer and maintain recent (and therefore relevant) reviews, reviews can only be submitted within a limited period of time (28 days) after a stay and each review will only be available for a limited period of time (24 months) after posting. The default ranking of the reviews is by date of submission relative to a few additional criteria (such as language, reviews with comments), whereas a review of a customer who [always] submits comprehensive and detailed reviews (aka "Property Scout") may be ranked on top. You have the option to choose various different forms of ranking and filter (e.g. by audience, date, language, score). Booking.com does allow the Trip Provider to respond to a review. We reserve the right to adjust, refuse, or remove reviews at our sole discretion insofar it violates our review policy. Booking.com does not compensate or otherwise reward a customer for completing a review. The guest review form should be regarded as a survey and does not include any (further commercial) offers, invitations, or incentives whatsoever. Booking.com undertakes to use its best efforts to monitor and remove reviews that include obscenities or the mention of an individual’s name or reference to stolen goods.

                    Booking.com will not accept reviews which include:

                    Profanity, sexually explicit, hate speech, discriminatory, threats, violence
                    Mention of full names, personal attack towards the staff
                    Promoting illegal activities (e.g. drugs, prostitution)
                    Sites, emails, and addresses, phone numbers, cc details
                    Politically sensitive comments
                    Booking.com and the Trip Provider are each entitled to terminate their relationship for whatever reason (including in the event of breach of contract or (filing for) bankruptcy) with due observance of the relevant notice period as agreed between both parties.

                    9. Disclaimer
                    Subject to the limitations set out in these terms and conditions and to the extent permitted by law, we will only be liable for direct damages actually suffered, paid, or incurred by you due to an attributable shortcoming of our obligations in respect to our services, up to an aggregate amount of the aggregate cost of your reservation as set out in the Trip Reservation confirmation email (whether for one event or series of connected events).

                    However and to the extent permitted by law, neither we nor any of our officers, directors, employees, representatives, subsidiaries, affiliated companies, distributors, affiliate (distribution) partners, licensees, agents, or others involved in creating, sponsoring, promoting, or otherwise making available the site and its contents will be liable for (i) any punitive, special, indirect, or consequential loss or damages, any loss of production, loss of profit, loss of revenue, loss of contract, loss of or damage to goodwill or reputation, loss of claim, (ii) any inaccuracy relating to the (descriptive) information (including rates, availability, and ratings) of the Trip Provider as made available on our Platform, (iii) the services rendered or the products offered by the Trip Provider or other business partners, (iv) any (direct, indirect, consequential, or punitive) damages, losses, or costs suffered, incurred, or paid by you, pursuant to, arising out of or in connection with the use, inability to use, or delay of our Platform, or (v) any (personal) injury, death, property damage, or other (direct, indirect, special, consequential, or punitive) damages, losses, or costs suffered, incurred or paid by you, whether due to (legal) acts, errors, breaches, (gross) negligence, willful misconduct, omissions, non-performance, misrepresentations, tort or strict liability by or (wholly or partly) attributable to the Trip Provider or any of our other business partners (including any of their employees, directors, officers, agents, representatives, subcontractors, or affiliated companies) whose products or service are (directly or indirectly) made available, offered, or promoted on or through the Platform, including any (partial) cancellation, overbooking, strike, force majeure, or any other event beyond our control.

                    Booking.com is not responsible (and disclaims any liability) for the use, validity, quality, suitability, fitness, and due disclosure of the Trip and makes no representations, warranties, or conditions of any kind in this respect, whether implied, statutory or otherwise, including any implied warranties of merchantability, title, non-infringement, or fitness for a particular purpose. You acknowledge and agree that the relevant Trip Provider is solely responsible and assumes all responsibility and liability in respect of the Trip (including any warranties and representations made by the Trip Provider). Booking.com is not a (re)seller of the Trip. Complaints or claims in respect of the Trip (including related to the offered (special/promotion) price, policy or specific requests made by Customers) are to be dealt with by the Trip Provider. Booking.com is not responsible for and disclaims any liability in respect of such complaints, claims, and (product) liabilities.

                    Whether or not the Trip Provider has charged you for your Trip, or if we are facilitating the payment of the (Trip) price or fee, you agree and acknowledge that the Trip Provider is at all times responsible for the collection, withholding, remittance, and payment of the applicable taxes due on the total amount of the (Trip) price or fee to the relevant tax authorities. Booking.com is not liable or responsible for the remittance, collection, withholding, or payment of the relevant taxes due on the (Trip) price or fee to the relevant tax authorities. Booking.com does not act as the merchant of record for any product or service made available on the Platform.

                    By uploading photos/images onto our system (for instance in addition to a review) you certify, warrant and agree that you own the copyright to the photos/images and that you agree that Booking.com may use the uploaded photos/images on its (mobile) website and app, and in (online/offline) promotional materials and publications and as Booking.com at its discretion sees fit. You are granting Booking.com a non-exclusive, worldwide, irrevocable, unconditional, perpetual right and license to use, reproduce, display, have reproduced, distribute, sublicense, communicate and make available the photos/images as Booking.com at its discretion sees fit. By uploading these photos/images the person uploading the picture(s) accepts full legal and moral responsibility of any and all legal claims that are made by any third parties (including, but not limited to, property owners) due to Booking.com publishing and using these photos/images. Booking.com does not own or endorse the photos/images that are uploaded. The truthfulness, validity and right to use of all photos/images is assumed by the person who uploaded the photo, and is not the responsibility of Booking.com. Booking.com disclaims all responsibility and liability for the pictures posted. The person who uploaded the photo warrants that the photos/images shall not contain any viruses, Trojan horses or infected files and shall not contain any pornographic, illegal, obscene, insulting, objectionable or inappropriate material and does not infringe any third party (intellectual property right, copyright or privacy) rights. Any photo/image that does not meet the aforesaid criteria will not be posted and/or can be removed/deleted by Booking.com at any time and without prior notice.

                    10. Intellectual Property Rights
                    Unless stated otherwise, the software required for our services or available at or used by our Platform and the intellectual property rights (including the copyrights) of the contents and information of and material on our Platform are owned by Booking.com B.V., its Trip Providers or providers.

                    Booking.com exclusively retains ownership of all rights, title and interest in and to (all intellectual property rights of) (the look and feel (including infrastructure) of) the Platform on which the service is made available (including the guest reviews and translated content) and you are not entitled to copy, scrape, (hyper-/deep)link to, publish, promote, market, integrate, utilize, combine or otherwise use the content (including any translations thereof and the guest reviews) or our brand without our express written permission. To the extent that you would (wholly or partly) use or combine our (translated) content (including guest reviews) or would otherwise own any intellectual property rights in the Platform or any (translated) content or guest reviews, you hereby assign, transfer and set over all such intellectual property rights to Booking.com. Any unlawful use or any of the aforementioned actions or behaviour will constitute a material infringement of our intellectual property rights (including copyright and database right).

                    11. Miscellaneous
                    To the extent permitted by law, these terms and conditions and the provision of our services shall be governed by and construed in accordance with Dutch law and any dispute arising out of these general terms and conditions and our services shall exclusively be submitted to the competent courts in Amsterdam, the Netherlands.

                    The original UK English version of these Terms and Conditions may have been translated into other languages. The translated version is a courtesy and office translation only and you cannot derive any rights from the translated version. In the event of a dispute about the contents or interpretation of these terms and conditions or inconsistency or discrepancy between the UK English version and any other language version of these terms and conditions, the UK English language version to the extent permitted by law shall apply, prevail and be conclusive. The UK English version is available on our Platform (by selecting "English (UK)" language) or shall be sent to you upon your written request.

                    If any provision of these terms and conditions is or becomes invalid, unenforceable or non-binding, you shall remain bound by all other provisions hereof. In such event, such invalid provision shall nonetheless be enforced to the fullest extent permitted by applicable law, and you will at least agree to accept a similar effect as the invalid, unenforceable or non-binding provision, given the contents and purpose of these terms and conditions.

                    12. About Booking.com and the support companies
                    The Trip Service is rendered by Booking.com B.V., which is a private limited liability company, incorporated under the laws of the Netherlands and having its offices at Herengracht 597, 1017 CE Amsterdam, the Netherlands and registered with the trade register of the Chamber of Commerce in Amsterdam under registration number 31047344. Our VAT registration number is NL805734958B01.

                    Booking.com has its headquarters in Amsterdam, the Netherlands and is supported by various affiliated group companies (the "support companies") throughout the world. The support companies only provide an internal supporting role to and for the benefit of Booking.com. Certain designated support companies render limited customer care support services (only by telephone). The support companies do not have any Platform (and do not in any way control, manage, maintain, or host the Platform). The support companies do not have any power or authority to render the Trip Service, to represent Booking.com, or to enter into any contract in the name of, for or on behalf of Booking.com. You do not have a (legal or contractual) relationship with the support companies. The support companies do not operate and are not authorized to act as any form of process or service agent of Booking.com. Booking.com does not accept nor assume any domicile at any place, location, or office in the world (also not at the office of its support companies), other than its registered office in Amsterdam.
                </p>
            </div>
        </div>
    </div>

    </div>
</section>
<!-- end about me-->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-6 heading">
                <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><div>About us<span>What we are?</span></div></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text_under_heading">
                <p>This is a student project made by Kaloyan Krasimirov Rachev and it's not for a real purposes. Used information in this website will be real (for e.g. destinations, prices, travel agents) but only for non-commerce situations. Terms and conditions, belongs to booking.com .Have fun !!!</p>
            </div>
        </div>
    </div>
</section>
<!-- end about me-->
@include('layouts.footer')